### ISSUE TITLE
Doesn't work inside `mat-sidenav-content`

### ISSUE THREAD

**Issue by anelad** [bikecoders/ngx-sticky#16]
It doesn't work inside `mat-sidenav-content`  when setting up like this

**app.component**
```html
<mat-sidenav-container>
  <mat-sidenav #sidenav>
      ......
  </mat-sidenav>

  <mat-sidenav-content>
    <div>
      <app-header></app-header>
      <router-outlet></router-outlet>
    </div>
    <app-footer></app-footer>
  </mat-sidenav-content>

</mat-sidenav-container>
```

**page.component:**
```html
<div class="section" fxFlexFill>
  <div #section class="section-row" fxLayout="row" fxLayout.gt-sm="row" fxLayout="column">
    <div class="content" fxLayout="column" fxFlex.gt-sm="70" fxFlex="100">
         ... some content ...
    </div>

    <div #scCont fxFlex.gt-sm="30" fxFlex="100" class="sidebar">
      <div ngxSticky [scrollContainer]="scCont" triggerOn="trigger-on" classWhenSticky="when-sticky">
            ... some content ...
      </div>
      <div id="trigger-on"></div>

    </div>

  </div>

</div>
```

**Comment by dianjuar** [comment]
Can you recreate your issue on [stackblitz](https://stackblitz.com/) ?

Will be more easy to see what could be problem

**Comment by anelad** [comment]
@dianjuar, I've searched the problem for 2 days and opened the issue, but after your response, I thought that "he claims it should work" and searched more, now I've found that the problem is in my old CSS. Closing the issue, sorry for interrupting.

**Comment by dianjuar** [comment]
You're welcome.

Provide stackblitz URL with the problem is a common practice to see what is going on and make live testing. I was not doubting about your problem, is just a better way to debug and is also interesting seeing how the package is being used, like user feedback.

If you have ANY questions about the usage or features of the package please feel free to open another issue.

I hope this package is helping you out :).
